version: "3"
networks:
  webserver:
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - webserver
    deploy:
      replicas: 5
      resources: 
        limits:
          cpus: 0.1
          memory: 50M
      restart_policy:
        condition: on-failure
      