version: "3.9"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - webserver
    deploy:
      placement: 
        constraints: 
          - node.labels.dc == UK
      replicas: 10
      resources: 
        limits:
          cpus: "0.1"
          memory: 50M
        reservations:
          cpus: "0.05"
          memory: 25M
      restart_policy:
        condition: on-failure
  db:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - webserver
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement: 
        constraints: [node.role == manager]
networks:
  webserver: